name: meteonet-web-app
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - autopep8=1.6.0
  - blas=1.0
  - bottleneck=1.3.5
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2023.01.10
  - certifi=2022.12.7
  - cffi=1.15.0
  - charset-normalizer=2.1.1
  - colorama=0.4.6
  - contourpy=1.0.5
  - cryptography=3.4.8
  - cycler=0.11.0
  - dbus=1.13.18
  - efficientnet-pytorch=0.7.1
  - expat=2.2.10
  - fontconfig=2.14.1
  - fonttools=4.25.0
  - freetype=2.10.4
  - future=0.18.3
  - giflib=5.2.1
  - glib=2.69.1
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - icu=58.2
  - idna=3.4
  - intel-openmp=2021.4.0
  - jpeg=9e
  - keyutils=1.6.1
  - kiwisolver=1.4.4
  - krb5=1.19.3
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libclang=10.0.1
  - libdeflate=1.8
  - libedit=3.1.20191231
  - libevent=2.1.12
  - libffi=3.4.2
  - libgcc-ng=11.2.0
  - libgfortran-ng=12.2.0
  - libgfortran5=12.2.0
  - libgomp=11.2.0
  - liblapack=3.9.0
  - libllvm10=10.0.1
  - libpng=1.6.37
  - libpq=12.9
  - libprotobuf=3.20.3
  - libstdcxx-ng=11.2.0
  - libtiff=4.5.0
  - libuuid=1.41.5
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libxcb=1.15
  - libxkbcommon=1.0.3
  - libxml2=2.9.14
  - libxslt=1.1.35
  - lz4-c=1.9.3
  - matplotlib=3.6.2
  - matplotlib-base=3.6.2
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - munch=2.5.0
  - munkres=1.1.4
  - ncurses=6.4
  - ninja=1.11.0
  - nspr=4.33
  - nss=3.74
  - numexpr=2.8.4
  - numpy=1.23.5
  - numpy-base=1.23.5
  - openssl=1.1.1s
  - packaging=22.0
  - pandas=1.5.2
  - pcre=8.45
  - pillow=9.3.0
  - pip=22.3.1
  - ply=3.11
  - pretrainedmodels=0.7.4
  - pycodestyle=2.10.0
  - pycparser=2.21
  - pyopenssl=20.0.1
  - pyparsing=3.0.9
  - pyqt=5.15.7
  - pysocks=1.7.1
  - python=3.10.9
  - python-dateutil=2.8.2
  - python_abi=3.10
  - pytorch=1.12.1
  - pytz=2022.7
  - pyyaml=6.0
  - qt-main=5.15.2
  - qt-webengine=5.15.9
  - qtwebkit=5.212
  - readline=8.2
  - requests=2.28.2
  - scipy=1.8.1
  - seaborn=0.12.2
  - segmentation-models-pytorch=0.3.1
  - setuptools=65.6.3
  - sip=6.6.2
  - six=1.16.0
  - sqlite=3.40.1
  - timm=0.4.12
  - tk=8.6.12
  - toml=0.10.2
  - torchvision=0.13.1
  - tornado=6.1
  - tqdm=4.64.1
  - typing-extensions=4.4.0
  - typing_extensions=4.4.0
  - urllib3=1.26.14
  - wheel=0.37.1
  - xz=5.2.10
  - yaml=0.2.5
  - zlib=1.2.13
  - zstd=1.5.2
  - pip:
    - altair==4.2.2
    - attrs==22.2.0
    - blinker==1.5
    - cachetools==5.3.0
    - click==8.1.3
    - decorator==5.1.1
    - entrypoints==0.4
    - gitdb==4.0.10
    - gitpython==3.1.30
    - importlib-metadata==6.0.0
    - jinja2==3.1.2
    - jsonschema==4.17.3
    - markdown-it-py==2.1.0
    - markupsafe==2.1.2
    - mdurl==0.1.2
    - protobuf==3.20.3
    - pyarrow==11.0.0
    - pydeck==0.8.0
    - pygments==2.14.0
    - pympler==1.0.1
    - pyqt5-sip==12.11.0
    - pyrsistent==0.19.3
    - pytz-deprecation-shim==0.1.0.post0
    - rich==13.3.1
    - semver==2.13.0
    - smmap==5.0.0
    - streamlit==1.18.1
    - streamlit-option-menu==0.3.2
    - toolz==0.12.0
    - tzdata==2022.7
    - tzlocal==4.2
    - validators==0.20.0
    - watchdog==2.2.1
    - zipp==3.13.0
